### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by poVoq** [sedenion/xows#2]
It seems a bit odd that there is no index file or a way to configure the websocket URL.

Could you please add some setup instructions?

Thanks!

**Comment by sedenion** [comment]
Hi,

Indeed it lack documentation, the project is at a very early stage. I just written a quick start guide, assuming you already have properly configured XMPP server and a web server:

https://github.com/sedenion/xows/wiki

**Comment by poVoq** [comment]
Thanks, got it to work. Looks really nice, but you should probably update the screenshots ;)

I guess federated MUCs don't work yet?

**Comment by sedenion** [comment]
To be honest I did not know that federated MUC existed. Anyway for now I am focused on continuing conventional MUC features implementation (role and affiliation management, room subscription, etc.).

**Comment by poVoq** [comment]
Ah, sorry. Missunderstanding. There is a standard for federated MUCS, but I simply meant joining MUCs on remote servers.

**Comment by sedenion** [comment]
Ok. Indeed there is currently no way to join a MUC room located in a third-party server. In fact the MUC philosophy of the Library is currently very "own-local-server" oriented, assuming that server already provide several public rooms, directly displayed by client, that user can join directly. I also though about a non-standard room identifier parsing mechanism (for example using dot as separator) to generate room hierarchy/grouping.
The goal is to offer an experience closer to what application such as Discord offer, rather than the old IRC paradigm.

Anyway, this may evolve in the future, this is mostly mater of user interface and philosophy, the backend client could, with small modifications, already join third-party MUC service rooms.

**Comment by sedenion** [comment]
If you are using files from the last Release it is possible you encountered a known bug: It crash if the XMPP server does not provide any additional services (such as MUC or HTTP Upload).

I just added HTML files examples for a typical setup in the repository. What you can try is to download the current repository files (all files) instead of the Release files.

**Comment by sedenion** [comment]
Ok, it is better to use "debug.html" file as model (more convenient for debugging), taking care to set the verbose level to 4, then copy past here the 5 - 6 last console output lines so I can understand what happen.

**Comment by sedenion** [comment]
Did you solved your infinite login issue ?

**Comment by poVoq** [comment]
I tried the debug version, but no difference. And while it is spinning the cancle button isn't working either making it really hard to catch any errors in the constantly moving browers console.

Does `Uncaught TypeError: iden[0] is undefined` tell you anything? That seems to be the only thing that might be an error?

**Comment by sedenion** [comment]
Yes, that tell me something, I know where the problem, is it is easy to fix, but I need console output log of the debug (verbose:4) version to understand exactly what happen. At this stage I think it is better you open a new Issue dedicated to this problem.
So I need you to try (and crash) to connect again using the debug version, then:

- Open browser developer tools and go to "Console" tab (you already know)
- Right-Click somewhere within the Console log, and hit "Save all messages to file" or "Save as.." (or something equivalent)
- Put the file as Attached file in the new Issue message.

If you have some privacy concern you can replace all occurrence of your server domain with "example.com" or something like this, I don't need such thing... I am also interesting by what the XMPP server software version you are using, if you know.

**Comment by poVoq** [comment]
Ejabberd 24.02 with an LDAP auth backend.

I'll share the console log in another thread later.

**Comment by poVoq** [comment]
There is really no possible way to share the browser log, it just gets into a super spammy endless loop during the entity discovery that never completes.

**Comment by sedenion** [comment]
with the latest repository version ?

**Comment by poVoq** [comment]
Yes, latest repository version.

**Comment by sedenion** [comment]
Ok, I just rewrite the services discovery process, please clone current repo and try again

**Comment by poVoq** [comment]
Great, it logs in now. thanks!
